/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas.Auxiliares;

import Clases.Usuario;
import Funcionalidades.PreferenciasUsuario;
import Ventanas.Errores.OcurreError;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JLabel;

/**
 *
 * @author ricar
 */
public class ConfirmarPreferencias extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarPreferencias
     */
    private int xmouse, ymouse;
    private Usuario user;

    public ConfirmarPreferencias(Usuario user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        mostrarPreferencias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_btn_SALIR = new javax.swing.JLabel();
        pnl_btn_salir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnl_btn_cancelar = new javax.swing.JPanel();
        lbl_btn_cancelar = new javax.swing.JLabel();
        pnl_btn_aceptar = new javax.swing.JPanel();
        lbl_btn_aceptar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_aerolinea = new javax.swing.JLabel();
        lbl_clase = new javax.swing.JLabel();
        lbl_comida = new javax.swing.JLabel();
        lbl_entretenimiento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_barra_salir = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 51, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deseas realizar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 240, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("   los siguientes cambios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 154, 240, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGO blanco pequenio 100x47.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 100, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FIDE AIRLINES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 20));

        lbl_btn_SALIR.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        lbl_btn_SALIR.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_SALIR.setText("X");
        lbl_btn_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseExited(evt);
            }
        });
        jPanel1.add(lbl_btn_SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        pnl_btn_salir.setBackground(new java.awt.Color(43, 51, 139));
        pnl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btn_salirMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 300));

        jLabel3.setText("Entretenimiento durante el vuelo: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 20));

        pnl_btn_cancelar.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_cancelar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lbl_btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_cancelar.setText("CANCELAR");
        lbl_btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_cancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_cancelarLayout = new javax.swing.GroupLayout(pnl_btn_cancelar);
        pnl_btn_cancelar.setLayout(pnl_btn_cancelarLayout);
        pnl_btn_cancelarLayout.setHorizontalGroup(
            pnl_btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnl_btn_cancelarLayout.setVerticalGroup(
            pnl_btn_cancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnl_btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 30));

        pnl_btn_aceptar.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_aceptar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lbl_btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_aceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_aceptar.setText("ACEPTAR");
        lbl_btn_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_aceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_aceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_aceptarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_aceptarLayout = new javax.swing.GroupLayout(pnl_btn_aceptar);
        pnl_btn_aceptar.setLayout(pnl_btn_aceptarLayout);
        pnl_btn_aceptarLayout.setHorizontalGroup(
            pnl_btn_aceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnl_btn_aceptarLayout.setVerticalGroup(
            pnl_btn_aceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnl_btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        jLabel8.setText("Aerolinea de preferencia:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel9.setText("Clase de preferencia: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel10.setText("Comida durante el vuelo:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, 20));

        lbl_aerolinea.setText("Aerolinea de preferencia:");
        jPanel2.add(lbl_aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 150, -1));

        lbl_clase.setText("Clase de preferencia: ");
        jPanel2.add(lbl_clase, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 150, 20));

        lbl_comida.setText("Comida durante el vuelo:");
        jPanel2.add(lbl_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, -1));

        lbl_entretenimiento.setText("Entretenimiento durante el vuelo: ");
        jPanel2.add(lbl_entretenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 140, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 340, 10));

        pnl_barra_salir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_barra_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMouseDragged(evt);
            }
        });
        pnl_barra_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_barra_salirLayout = new javax.swing.GroupLayout(pnl_barra_salir);
        pnl_barra_salir.setLayout(pnl_barra_salirLayout);
        pnl_barra_salirLayout.setHorizontalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        pnl_barra_salirLayout.setVerticalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(pnl_barra_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_btn_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_btn_SALIRMouseClicked

    private void lbl_btn_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.WHITE);
        lbl_btn_SALIR.setForeground(Color.blue);
    }//GEN-LAST:event_lbl_btn_SALIRMouseEntered

    private void lbl_btn_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(new Color(43, 51, 139));
        lbl_btn_SALIR.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_btn_SALIRMouseExited

    private void pnl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btn_salirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btn_salirMouseEntered

    private void pnl_barra_salirMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salirMouseDragged

    private void pnl_barra_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_barra_salirMousePressed

    private void lbl_btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_cancelarMouseEntered
        // TODO add your handling code here:

        pnl_btn_cancelar.setBackground(new Color(79, 93, 255));

    }//GEN-LAST:event_lbl_btn_cancelarMouseEntered

    private void lbl_btn_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_cancelarMouseExited
        pnl_btn_cancelar.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_cancelarMouseExited

    private void lbl_btn_aceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_aceptarMouseEntered
        // TODO add your handling code here:
        pnl_btn_aceptar.setBackground(new Color(79, 93, 255));

    }//GEN-LAST:event_lbl_btn_aceptarMouseEntered

    private void lbl_btn_aceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_aceptarMouseExited
        pnl_btn_aceptar.setBackground(new Color(43, 51, 139));

    }//GEN-LAST:event_lbl_btn_aceptarMouseExited

    private void lbl_btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_cancelarMouseClicked
        PreferenciasUsuario n = new PreferenciasUsuario(user);
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_btn_cancelarMouseClicked

    private void lbl_btn_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_aceptarMouseClicked
        try {

            Connection nuevaConexion = DriverManager.getConnection(
                    "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                    "root",
                    "Fide123.");

            String update_preferencias = "UPDATE usuarios SET aerolineaspreferidas = ? "
                    + ",clasepreferida = ?, comida = ?, entretenimiento = ?  WHERE correoelectronico = ?";

            PreparedStatement nuevoStatementePreparado = nuevaConexion.prepareStatement(update_preferencias);

            nuevoStatementePreparado.setString(1, user.getAerolineaspreferidas());
            nuevoStatementePreparado.setString(2, user.getClasepreferida());
            nuevoStatementePreparado.setString(3, user.getComida());
            nuevoStatementePreparado.setString(4, user.getEntretenimiento());
            nuevoStatementePreparado.setString(5, user.getCorreoelectronico());
            nuevoStatementePreparado.executeUpdate();
            
            Usuario preferenciasAnteriores = new Usuario(
                    user.getAerolineaspreferidas(), 
                    user.getClasepreferida(), 
                    user.getComida(), 
                    user.getEntretenimiento());
            
            user.setAerolineaspreferidas(preferenciasAnteriores.getAerolineaspreferidas());
            user.setClasepreferida(preferenciasAnteriores.getClasepreferida());
            user.setComida(preferenciasAnteriores.getComida());
            user.setEntretenimiento(preferenciasAnteriores.getEntretenimiento());
            nuevaConexion.close();
            nuevoStatementePreparado.close();
            this.dispose();

            PreferenciasActualizadas abrirPreferenciasActualizadas = new PreferenciasActualizadas(user);
            abrirPreferenciasActualizadas.setVisible(true);

     

        } catch (Exception ex) {


            OcurreError error = new OcurreError();
            error.setVisible(true);
        }
        this.dispose();


    }//GEN-LAST:event_lbl_btn_aceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public void mostrarPreferencias() {

        lbl_aerolinea.setText(user.getAerolineaspreferidas());
        lbl_clase.setText(user.getClasepreferida());
        lbl_comida.setText(user.getComida());
        lbl_entretenimiento.setText(user.getEntretenimiento());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPreferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarPreferencias(null).setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_aerolinea;
    private javax.swing.JLabel lbl_btn_SALIR;
    private javax.swing.JLabel lbl_btn_aceptar;
    private javax.swing.JLabel lbl_btn_cancelar;
    private javax.swing.JLabel lbl_clase;
    private javax.swing.JLabel lbl_comida;
    private javax.swing.JLabel lbl_entretenimiento;
    private javax.swing.JPanel pnl_barra_salir;
    private javax.swing.JPanel pnl_btn_aceptar;
    private javax.swing.JPanel pnl_btn_cancelar;
    private javax.swing.JPanel pnl_btn_salir;
    // End of variables declaration//GEN-END:variables
}
