/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Clases.Vuelos;
import Ventanas.Auxiliares.VueloAgregado;
import Ventanas.InicioSesion.InicioSesion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author ricar
 */
public class agregarVuelos extends javax.swing.JFrame {

    /**
     * Creates new form agregarVuelos
     */
    int xmouse, ymouse;
    String comida, entretenimiento;

    public agregarVuelos() {
        initComponents();
        this.setLocationRelativeTo(null);
        restablecerCampos();

        cbx_HoraSalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lbl_duracion.setText(calcularDiferencia() + " horas");
            }
        });

        cbx_HoraLlegada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                calcularDiferencia();
                lbl_duracion.setText(calcularDiferencia() + " horas");
            }
        });
        txt_Asientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });

        chbx_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (chbx_comida.isSelected()) {
                    comida = "Si";
                } else {
                    comida = "No";
                }
            }
        });

        chbx_entretenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (chbx_entretenimiento.isSelected()) {
                    entretenimiento = "Si";
                } else {
                    entretenimiento = "No";
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_btn_salir = new javax.swing.JPanel();
        lbl_btn_salir = new javax.swing.JLabel();
        pnl_barra_salida = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Origen = new javax.swing.JTextField();
        txt_Asientos = new javax.swing.JTextField();
        txt_Destino = new javax.swing.JTextField();
        txt_Aerolinea = new javax.swing.JTextField();
        txt_Precio = new javax.swing.JTextField();
        lbl_duracion = new javax.swing.JLabel();
        jcal_fechaSalida = new com.toedter.calendar.JDateChooser();
        cbx_HoraSalida = new javax.swing.JComboBox<>();
        cbx_HoraLlegada = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnl_btn_agregarVuelo = new javax.swing.JPanel();
        lbl_btn_agregarVuelo = new javax.swing.JLabel();
        chbx_entretenimiento = new javax.swing.JCheckBox();
        chbx_comida = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 51, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_btn_salir.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_salir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbl_btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_salir.setText("X");
        lbl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnl_barra_salida.setBackground(new java.awt.Color(43, 51, 139));
        pnl_barra_salida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salidaMouseDragged(evt);
            }
        });
        pnl_barra_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salidaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_barra_salidaLayout = new javax.swing.GroupLayout(pnl_barra_salida);
        pnl_barra_salida.setLayout(pnl_barra_salidaLayout);
        pnl_barra_salidaLayout.setHorizontalGroup(
            pnl_barra_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnl_barra_salidaLayout.setVerticalGroup(
            pnl_barra_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_barra_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jPanel2.setBackground(new java.awt.Color(43, 51, 139));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Vuelos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 50));

        txt_Origen.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txt_Origen.setForeground(java.awt.Color.lightGray);
        txt_Origen.setText("Origen");
        txt_Origen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_OrigenMouseClicked(evt);
            }
        });
        txt_Origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_OrigenKeyPressed(evt);
            }
        });
        jPanel1.add(txt_Origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 430, 35));

        txt_Asientos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txt_Asientos.setForeground(java.awt.Color.lightGray);
        txt_Asientos.setText("Asientos");
        txt_Asientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_AsientosMouseClicked(evt);
            }
        });
        jPanel1.add(txt_Asientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 200, 35));

        txt_Destino.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txt_Destino.setForeground(java.awt.Color.lightGray);
        txt_Destino.setText("Destino");
        txt_Destino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_DestinoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_DestinoMousePressed(evt);
            }
        });
        jPanel1.add(txt_Destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 430, 35));

        txt_Aerolinea.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txt_Aerolinea.setForeground(java.awt.Color.lightGray);
        txt_Aerolinea.setText("Aerolinea");
        txt_Aerolinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_AerolineaMouseClicked(evt);
            }
        });
        jPanel1.add(txt_Aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 200, 35));

        txt_Precio.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txt_Precio.setForeground(java.awt.Color.lightGray);
        txt_Precio.setText("Precio");
        txt_Precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PrecioMouseClicked(evt);
            }
        });
        jPanel1.add(txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 200, 35));

        lbl_duracion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lbl_duracion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_duracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_duracion.setText("00:00");
        jPanel1.add(lbl_duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 70, -1));
        jPanel1.add(jcal_fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 200, 35));

        cbx_HoraSalida.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cbx_HoraSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00 am", "01:00 am", "02:00 am", "03:00 am", "04:00 am", "05:00 am", "06:00 am", "07:00 am", "08:00 am", "09:00 am", "10:00 am", "11:00 am", "12:00 pm", "01:00 pm", "02:00 pm", "03:00 pm", "04:00 pm", "05:00 pm", "06:00 pm", "07:00 pm", "08:00 pm", "09:00 pm", "10:00 pm", "11:00 pm" }));
        jPanel1.add(cbx_HoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 90, 35));

        cbx_HoraLlegada.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cbx_HoraLlegada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00 am", "01:00 am", "02:00 am", "03:00 am", "04:00 am", "05:00 am", "06:00 am", "07:00 am", "08:00 am", "09:00 am", "10:00 am", "11:00 am", "12:00 pm", "01:00 pm", "02:00 pm", "03:00 pm", "04:00 pm", "05:00 pm", "06:00 pm", "07:00 pm", "08:00 pm", "09:00 pm", "10:00 pm", "11:00 pm" }));
        jPanel1.add(cbx_HoraLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 90, 35));

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hora Llegada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 70, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duración:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 70, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hora Salida");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 70, -1));

        pnl_btn_agregarVuelo.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_agregarVuelo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lbl_btn_agregarVuelo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_agregarVuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_agregarVuelo.setText("Agregar Vuelo");
        lbl_btn_agregarVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_agregarVueloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_agregarVueloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_agregarVueloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_agregarVueloLayout = new javax.swing.GroupLayout(pnl_btn_agregarVuelo);
        pnl_btn_agregarVuelo.setLayout(pnl_btn_agregarVueloLayout);
        pnl_btn_agregarVueloLayout.setHorizontalGroup(
            pnl_btn_agregarVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_agregarVueloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_agregarVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_agregarVueloLayout.setVerticalGroup(
            pnl_btn_agregarVueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_agregarVuelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_btn_agregarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 200, 35));

        chbx_entretenimiento.setBackground(new java.awt.Color(43, 51, 139));
        chbx_entretenimiento.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        chbx_entretenimiento.setForeground(new java.awt.Color(255, 255, 255));
        chbx_entretenimiento.setText("Servicio de Entretenimiento");
        jPanel1.add(chbx_entretenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 180, -1));

        chbx_comida.setBackground(new java.awt.Color(43, 51, 139));
        chbx_comida.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        chbx_comida.setForeground(new java.awt.Color(255, 255, 255));
        chbx_comida.setText("Servicio de Comida");
        chbx_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbx_comidaActionPerformed(evt);
            }
        });
        jPanel1.add(chbx_comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_barra_salidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salidaMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_barra_salidaMousePressed

    private void pnl_barra_salidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salidaMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salidaMouseDragged

    private void lbl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.white);
        lbl_btn_salir.setForeground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_salirMouseEntered

    private void lbl_btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseClicked
        // TODO add your handling code here:

        this.dispose();
        InicioSesion n = new InicioSesion();
        n.setVisible(true);
    }//GEN-LAST:event_lbl_btn_salirMouseClicked

    private void lbl_btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(new Color(43, 51, 139));
        lbl_btn_salir.setForeground(Color.white);
    }//GEN-LAST:event_lbl_btn_salirMouseExited

    private void lbl_btn_agregarVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_agregarVueloMouseClicked

        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

        Vuelos vuelo = new Vuelos();
        vuelo.setOrigen(txt_Origen.getText());
        vuelo.setDestino(txt_Destino.getText());
        vuelo.setAerolinea(txt_Aerolinea.getText());
        vuelo.setTotalasientos(Integer.parseInt(txt_Asientos.getText()));
        vuelo.setPrecioBoleto(validarPrecio());
        vuelo.setFechaSalida(formatoFecha.format(jcal_fechaSalida.getCalendar().getTime()));
        vuelo.setHoraSalida(cbx_HoraSalida.getSelectedItem().toString());
        vuelo.setHoraLlegada(cbx_HoraLlegada.getSelectedItem().toString());
        vuelo.setDuracion(lbl_duracion.getText());
        vuelo.setServicioComida(comida);
        vuelo.setServicioEntretenimiento(entretenimiento);

        System.out.println(vuelo.getOrigen());
        System.out.println(vuelo.getDestino());
        System.out.println(vuelo.getAerolinea());
        System.out.println(vuelo.getTotalasientos());
        System.out.println(vuelo.getPrecioBoleto());
        System.out.println(vuelo.getFechaSalida());
        System.out.println(vuelo.getHoraSalida());
        System.out.println(vuelo.getHoraLlegada());
        System.out.println(vuelo.getDuracion());
        System.out.println(vuelo.getServicioComida());
        System.out.println(vuelo.getServicioEntretenimiento());

        try {
            Connection nuevaConexion = DriverManager.getConnection(
                    "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                    "root",
                    "Fide123.");

            String Insert_vuelo = "INSERT INTO vuelos(origen, destino, precio, "
                    + "fechasalida, aerolinea, horasalida, horallegada, "
                    + "duracion, serviciocomida, servicioentretenimiento, asientos)"
                    + "VALUES(?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement nuevoPreparedStatement = nuevaConexion.prepareStatement(Insert_vuelo);

            nuevoPreparedStatement.setString(1, vuelo.getOrigen());
            nuevoPreparedStatement.setString(2, vuelo.getDestino());
            nuevoPreparedStatement.setString(3, vuelo.getPrecioBoleto() + "");
            nuevoPreparedStatement.setString(4, vuelo.getFechaSalida());
            nuevoPreparedStatement.setString(5, vuelo.getAerolinea());
            nuevoPreparedStatement.setString(6, vuelo.getHoraSalida());
            nuevoPreparedStatement.setString(7, vuelo.getHoraLlegada());
            nuevoPreparedStatement.setString(8, vuelo.getDuracion());
            nuevoPreparedStatement.setString(9, vuelo.getServicioComida());
            nuevoPreparedStatement.setString(10, vuelo.getServicioEntretenimiento());
            nuevoPreparedStatement.setString(11, vuelo.getTotalasientos() + "");

            nuevoPreparedStatement.executeUpdate();

            nuevaConexion.close();
            nuevoPreparedStatement.close();

            VueloAgregado n = new VueloAgregado();
            n.setVisible(true);

            restablecerCampos();
        } catch (SQLException ex) {
            Logger.getLogger(agregarVuelos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_lbl_btn_agregarVueloMouseClicked

    private void chbx_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbx_comidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbx_comidaActionPerformed

    private void lbl_btn_agregarVueloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_agregarVueloMouseEntered
        pnl_btn_agregarVuelo.setBackground(new Color(79, 93, 255));

    }//GEN-LAST:event_lbl_btn_agregarVueloMouseEntered

    private void lbl_btn_agregarVueloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_agregarVueloMouseExited
        pnl_btn_agregarVuelo.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_agregarVueloMouseExited

    private void txt_OrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_OrigenMouseClicked
        if (txt_Origen.getText().equals("Origen")) {
            txt_Origen.setText("");
            txt_Origen.setForeground(Color.BLACK);
        } else if (txt_Origen.getText().isEmpty()) {
            txt_Origen.setText("Origen");
            txt_Origen.setForeground(Color.LIGHT_GRAY);
        }

        if (txt_Destino.getText().isEmpty()) {
            txt_Destino.setForeground(Color.LIGHT_GRAY);
            txt_Destino.setText("Destino");
        }

        if (txt_Aerolinea.getText().isEmpty()) {
            txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
            txt_Aerolinea.setText("Aerolinea");
        }

        if (txt_Asientos.getText().isEmpty()) {
            txt_Asientos.setForeground(Color.LIGHT_GRAY);
            txt_Asientos.setText("Asientos");
        }

        if (txt_Precio.getText().isEmpty()) {
            txt_Precio.setForeground(Color.LIGHT_GRAY);
            txt_Precio.setText("Precio");
        }
    }//GEN-LAST:event_txt_OrigenMouseClicked

    private void txt_DestinoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DestinoMousePressed

    }//GEN-LAST:event_txt_DestinoMousePressed

    private void txt_AerolineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_AerolineaMouseClicked
        if (txt_Aerolinea.getText().equals("Aerolinea")) {
            txt_Aerolinea.setText("");
            txt_Aerolinea.setForeground(Color.BLACK);
        } else if (txt_Aerolinea.getText().isEmpty()) {
            txt_Aerolinea.setText("Aerolinea");
            txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
        }

        if (txt_Origen.getText().isEmpty()) {
            txt_Origen.setForeground(Color.LIGHT_GRAY);
            txt_Origen.setText("Origen");
        }

        if (txt_Destino.getText().isEmpty()) {
            txt_Destino.setForeground(Color.LIGHT_GRAY);
            txt_Destino.setText("Destino");
        }

        if (txt_Asientos.getText().isEmpty()) {
            txt_Asientos.setForeground(Color.LIGHT_GRAY);
            txt_Asientos.setText("Asientos");
        }

        if (txt_Precio.getText().isEmpty()) {
            txt_Precio.setForeground(Color.LIGHT_GRAY);
            txt_Precio.setText("Precio");
        }
    }//GEN-LAST:event_txt_AerolineaMouseClicked

    private void txt_DestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_DestinoMouseClicked
        if (txt_Destino.getText().equals("Destino")) {
            txt_Destino.setText("");
            txt_Destino.setForeground(Color.BLACK);
        } else if (txt_Destino.getText().isEmpty()) {
            txt_Destino.setText("Destino");
            txt_Destino.setForeground(Color.LIGHT_GRAY);
        }

        if (txt_Origen.getText().isEmpty()) {
            txt_Origen.setForeground(Color.LIGHT_GRAY);
            txt_Origen.setText("Origen");
        }

        if (txt_Aerolinea.getText().isEmpty()) {
            txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
            txt_Aerolinea.setText("Aerolinea");
        }

        if (txt_Asientos.getText().isEmpty()) {
            txt_Asientos.setForeground(Color.LIGHT_GRAY);
            txt_Asientos.setText("Asientos");
        }

        if (txt_Precio.getText().isEmpty()) {
            txt_Precio.setForeground(Color.LIGHT_GRAY);
            txt_Precio.setText("Precio");
        }
    }//GEN-LAST:event_txt_DestinoMouseClicked

    private void txt_AsientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_AsientosMouseClicked
        if (txt_Asientos.getText().equals("Asientos")) {
            txt_Asientos.setText("");
            txt_Asientos.setForeground(Color.BLACK);
        } else if (txt_Asientos.getText().isEmpty()) {
            txt_Asientos.setText("Asientos");
            txt_Asientos.setForeground(Color.LIGHT_GRAY);
        }

        if (txt_Origen.getText().isEmpty()) {
            txt_Origen.setForeground(Color.LIGHT_GRAY);
            txt_Origen.setText("Origen");
        }

        if (txt_Destino.getText().isEmpty()) {
            txt_Destino.setForeground(Color.LIGHT_GRAY);
            txt_Destino.setText("Destino");
        }

        if (txt_Aerolinea.getText().isEmpty()) {
            txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
            txt_Aerolinea.setText("Aerolinea");
        }

        if (txt_Precio.getText().isEmpty()) {
            txt_Precio.setForeground(Color.LIGHT_GRAY);
            txt_Precio.setText("Precio");
        }
    }//GEN-LAST:event_txt_AsientosMouseClicked

    private void txt_PrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PrecioMouseClicked
        if (txt_Precio.getText().equals("Precio")) {
            txt_Precio.setText("");
            txt_Precio.setForeground(Color.BLACK);
        } else if (txt_Precio.getText().isEmpty()) {
            txt_Precio.setText("Precio");
            txt_Precio.setForeground(Color.LIGHT_GRAY);
        }

        if (txt_Origen.getText().isEmpty()) {
            txt_Origen.setForeground(Color.LIGHT_GRAY);
            txt_Origen.setText("Origen");
        }

        if (txt_Destino.getText().isEmpty()) {
            txt_Destino.setForeground(Color.LIGHT_GRAY);
            txt_Destino.setText("Destino");
        }

        if (txt_Aerolinea.getText().isEmpty()) {
            txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
            txt_Aerolinea.setText("Aerolinea");
        }

        if (txt_Asientos.getText().isEmpty()) {
            txt_Asientos.setForeground(Color.LIGHT_GRAY);
            txt_Asientos.setText("Asientos");
        }
    }//GEN-LAST:event_txt_PrecioMouseClicked

    private void txt_OrigenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_OrigenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OrigenKeyPressed

    public double validarPrecio() {

        String precio = txt_Precio.getText();
        double valorNumerico = 0;

        try {
            if (precio != null && !precio.isEmpty() && precio.matches("\\d+")) {

                valorNumerico = Double.parseDouble(precio);

            }
        } catch (NumberFormatException e) {
            System.out.println(e);
        }

        return valorNumerico;
    }

    public int calcularDiferencia() {
        String hora1 = cbx_HoraSalida.getSelectedItem().toString();
        String hora2 = cbx_HoraLlegada.getSelectedItem().toString();

        int hora24h_1 = convertirA24Horas(hora1);

        int hora24h_2 = convertirA24Horas(hora2);

        int diferencia = hora24h_2 - hora24h_1;

        if (diferencia < 0) {
            diferencia += 24;
        }

        return diferencia;

    }

    private int convertirA24Horas(String horaStr) {

        String[] partes = horaStr.split(" ");
        String[] horaMinuto = partes[0].split(":");

        int hora12h = Integer.parseInt(horaMinuto[0]);
        String indicador = partes[1].trim();

        int hora24h = (hora12h == 12 && indicador.equalsIgnoreCase("am")) ? 0 : hora12h;
        if (indicador.equalsIgnoreCase("pm") && hora12h != 12) {
            hora24h += 12;
        }

        return hora24h;
    }

    public void restablecerCampos() {
        txt_Aerolinea.setText("Aerolinea");
        txt_Aerolinea.setForeground(Color.LIGHT_GRAY);
        txt_Asientos.setText("Asientos");
        txt_Asientos.setForeground(Color.LIGHT_GRAY);
        txt_Destino.setText("Destino");
        txt_Destino.setForeground(Color.LIGHT_GRAY);
        txt_Origen.setText("Origen");
        txt_Origen.setForeground(Color.LIGHT_GRAY);
        txt_Precio.setText("Precio");
        txt_Precio.setForeground(Color.LIGHT_GRAY);

        jcal_fechaSalida.setDate(null);
        cbx_HoraLlegada.setSelectedIndex(0);
        cbx_HoraSalida.setSelectedIndex(0);

        chbx_comida.setSelected(false);
        chbx_entretenimiento.setSelected(false);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarVuelos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarVuelos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarVuelos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarVuelos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_HoraLlegada;
    private javax.swing.JComboBox<String> cbx_HoraSalida;
    private javax.swing.JCheckBox chbx_comida;
    private javax.swing.JCheckBox chbx_entretenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jcal_fechaSalida;
    private javax.swing.JLabel lbl_btn_agregarVuelo;
    private javax.swing.JLabel lbl_btn_salir;
    private javax.swing.JLabel lbl_duracion;
    private javax.swing.JPanel pnl_barra_salida;
    private javax.swing.JPanel pnl_btn_agregarVuelo;
    private javax.swing.JPanel pnl_btn_salir;
    private javax.swing.JTextField txt_Aerolinea;
    private javax.swing.JTextField txt_Asientos;
    private javax.swing.JTextField txt_Destino;
    private javax.swing.JTextField txt_Origen;
    private javax.swing.JTextField txt_Precio;
    // End of variables declaration//GEN-END:variables
}
