/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas.InicioSesion;

import Admin.agregarVuelos;
import Clases.Usuario;
import Ventanas.Errores.CredencialesIncorrectas;
import Ventanas.Errores.contraseniasDiferentes;
import Ventanas.Registro.Registro;
import Ventanas.VentanaPrincipal.VentanaPrincipal;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    int xmouse, ymouse;

    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnl_Azul_IniciarSesion = new javax.swing.JPanel();
        lbl_Iniciar_Sesion = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        txf_correo_electronico_IniciarSesion = new javax.swing.JTextField();
        pf_contrasenia_IniciarSesion = new javax.swing.JPasswordField();
        pnl_btn_Acceder = new javax.swing.JPanel();
        lbl_btn_Acceder = new javax.swing.JLabel();
        lbl_olvide_mi_contrasenia = new javax.swing.JLabel();
        pnl_btn_Registrarse_IniciarSesion = new javax.swing.JPanel();
        lbl_btn_Registrarse_IniciarSesion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        chbx_adminLogin = new javax.swing.JCheckBox();
        pnl_barra_salir = new javax.swing.JPanel();
        pnl_btn_salir = new javax.swing.JPanel();
        lbl_btn_SALIR = new javax.swing.JLabel();
        lbl_fideairlines = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(null);

        pnl_Azul_IniciarSesion.setBackground(new java.awt.Color(43, 51, 139));
        pnl_Azul_IniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Iniciar_Sesion.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lbl_Iniciar_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Iniciar_Sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Iniciar_Sesion.setText("Iniciar Sesión");
        pnl_Azul_IniciarSesion.add(lbl_Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 330, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Azul_IniciarSesion.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 280, 30));

        txf_correo_electronico_IniciarSesion.setBackground(new java.awt.Color(43, 51, 139));
        txf_correo_electronico_IniciarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txf_correo_electronico_IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        txf_correo_electronico_IniciarSesion.setText("Correo Electronico");
        txf_correo_electronico_IniciarSesion.setBorder(null);
        txf_correo_electronico_IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txf_correo_electronico_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txf_correo_electronico_IniciarSesionMousePressed(evt);
            }
        });
        txf_correo_electronico_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_correo_electronico_IniciarSesionActionPerformed(evt);
            }
        });
        pnl_Azul_IniciarSesion.add(txf_correo_electronico_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 300, 40));

        pf_contrasenia_IniciarSesion.setBackground(new java.awt.Color(43, 51, 139));
        pf_contrasenia_IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        pf_contrasenia_IniciarSesion.setText("********");
        pf_contrasenia_IniciarSesion.setBorder(null);
        pf_contrasenia_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pf_contrasenia_IniciarSesionMousePressed(evt);
            }
        });
        pnl_Azul_IniciarSesion.add(pf_contrasenia_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, 40));

        pnl_btn_Acceder.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_Acceder.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbl_btn_Acceder.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_Acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_Acceder.setText("Acceder");
        lbl_btn_Acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_Acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_AccederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_AccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_AccederMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_AccederLayout = new javax.swing.GroupLayout(pnl_btn_Acceder);
        pnl_btn_Acceder.setLayout(pnl_btn_AccederLayout);
        pnl_btn_AccederLayout.setHorizontalGroup(
            pnl_btn_AccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_Acceder, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnl_btn_AccederLayout.setVerticalGroup(
            pnl_btn_AccederLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_Acceder, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnl_Azul_IniciarSesion.add(pnl_btn_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 40));

        lbl_olvide_mi_contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_olvide_mi_contrasenia.setText("Olvidé mi contraseña");
        lbl_olvide_mi_contrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_Azul_IniciarSesion.add(lbl_olvide_mi_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        pnl_btn_Registrarse_IniciarSesion.setBackground(new java.awt.Color(43, 51, 139));
        pnl_btn_Registrarse_IniciarSesion.setPreferredSize(new java.awt.Dimension(130, 40));

        lbl_btn_Registrarse_IniciarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbl_btn_Registrarse_IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_Registrarse_IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_Registrarse_IniciarSesion.setText("Registrarse");
        lbl_btn_Registrarse_IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_Registrarse_IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_Registrarse_IniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_Registrarse_IniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_Registrarse_IniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_Registrarse_IniciarSesionLayout = new javax.swing.GroupLayout(pnl_btn_Registrarse_IniciarSesion);
        pnl_btn_Registrarse_IniciarSesion.setLayout(pnl_btn_Registrarse_IniciarSesionLayout);
        pnl_btn_Registrarse_IniciarSesionLayout.setHorizontalGroup(
            pnl_btn_Registrarse_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_Registrarse_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnl_btn_Registrarse_IniciarSesionLayout.setVerticalGroup(
            pnl_btn_Registrarse_IniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_btn_Registrarse_IniciarSesionLayout.createSequentialGroup()
                .addComponent(lbl_btn_Registrarse_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_Azul_IniciarSesion.add(pnl_btn_Registrarse_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Azul_IniciarSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 20));

        chbx_adminLogin.setBackground(new java.awt.Color(43, 51, 139));
        chbx_adminLogin.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        chbx_adminLogin.setForeground(new java.awt.Color(255, 255, 255));
        chbx_adminLogin.setText("Iniciar como Admin");
        pnl_Azul_IniciarSesion.add(chbx_adminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        background.add(pnl_Azul_IniciarSesion);
        pnl_Azul_IniciarSesion.setBounds(470, 0, 330, 500);

        pnl_barra_salir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_barra_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMouseDragged(evt);
            }
        });
        pnl_barra_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMousePressed(evt);
            }
        });

        pnl_btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btn_salirMouseEntered(evt);
            }
        });

        lbl_btn_SALIR.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        lbl_btn_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_SALIR.setText("X");
        lbl_btn_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_barra_salirLayout = new javax.swing.GroupLayout(pnl_barra_salir);
        pnl_barra_salir.setLayout(pnl_barra_salirLayout);
        pnl_barra_salirLayout.setHorizontalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_salirLayout.createSequentialGroup()
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 770, Short.MAX_VALUE))
        );
        pnl_barra_salirLayout.setVerticalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(pnl_barra_salir);
        pnl_barra_salir.setBounds(0, 0, 800, 30);

        lbl_fideairlines.setBackground(new java.awt.Color(43, 51, 139));
        lbl_fideairlines.setFont(new java.awt.Font("Roboto Medium", 2, 36)); // NOI18N
        lbl_fideairlines.setForeground(new java.awt.Color(43, 51, 139));
        lbl_fideairlines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fideairlines.setText("FIDE AIRLINES");
        background.add(lbl_fideairlines);
        lbl_fideairlines.setBounds(-30, 200, 470, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/logo azul 2.png"))); // NOI18N
        background.add(jLabel2);
        jLabel2.setBounds(80, 140, 360, 210);

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_correo_electronico_IniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_correo_electronico_IniciarSesionMousePressed

        if (txf_correo_electronico_IniciarSesion.getText().isEmpty()) {
            txf_correo_electronico_IniciarSesion.setForeground(Color.WHITE);
            txf_correo_electronico_IniciarSesion.setText("Correo Electronico");
        } else if (txf_correo_electronico_IniciarSesion.getText().equals("Correo Electronico")) {
            txf_correo_electronico_IniciarSesion.setText("");
            txf_correo_electronico_IniciarSesion.setForeground(Color.WHITE);
        }

        if (String.valueOf(pf_contrasenia_IniciarSesion.getPassword()).isEmpty()) {
            pf_contrasenia_IniciarSesion.setText("********");
            pf_contrasenia_IniciarSesion.setForeground(Color.WHITE);
        }

    }//GEN-LAST:event_txf_correo_electronico_IniciarSesionMousePressed

    private void txf_correo_electronico_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_correo_electronico_IniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_correo_electronico_IniciarSesionActionPerformed

    private void pf_contrasenia_IniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_contrasenia_IniciarSesionMousePressed
        if (String.valueOf(pf_contrasenia_IniciarSesion.getPassword()).equals("********")) {
            pf_contrasenia_IniciarSesion.setText("");
            pf_contrasenia_IniciarSesion.setForeground(Color.WHITE);
        } else if (String.valueOf(pf_contrasenia_IniciarSesion.getPassword()).isEmpty()) {
            pf_contrasenia_IniciarSesion.setText("********");
            pf_contrasenia_IniciarSesion.setForeground(Color.WHITE);
        }

        if (txf_correo_electronico_IniciarSesion.getText().isEmpty()) {
            txf_correo_electronico_IniciarSesion.setForeground(Color.WHITE);
            txf_correo_electronico_IniciarSesion.setText("Correo Electronico");
        }
    }//GEN-LAST:event_pf_contrasenia_IniciarSesionMousePressed

    private void lbl_btn_AccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_AccederMouseEntered
        pnl_btn_Acceder.setBackground(new Color(79, 93, 255));
    }//GEN-LAST:event_lbl_btn_AccederMouseEntered

    private void lbl_btn_AccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_AccederMouseExited

        pnl_btn_Acceder.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_AccederMouseExited

    private void lbl_btn_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_btn_SALIRMouseClicked

    private void lbl_btn_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.blue);
        lbl_btn_SALIR.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_btn_SALIRMouseEntered

    private void lbl_btn_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.white);
        lbl_btn_SALIR.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbl_btn_SALIRMouseExited

    private void pnl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btn_salirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btn_salirMouseEntered

    private void pnl_barra_salirMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salirMouseDragged

    private void pnl_barra_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_barra_salirMousePressed

    private void lbl_btn_AccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_AccederMouseClicked
        if (chbx_adminLogin.isSelected()) {
            try {

                Connection nuevaConexion = DriverManager.getConnection(
                        "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                        "root",
                        "Fide123.");

                String consulta_inicio = "SELECT correoelectronico,password"
                        + " FROM admins WHERE correoelectronico = ? AND password = ?";

                PreparedStatement nuevoStatementPreparado = nuevaConexion.prepareStatement(consulta_inicio);

                nuevoStatementPreparado.setString(1, txf_correo_electronico_IniciarSesion.getText());

                nuevoStatementPreparado.setString(2, String.copyValueOf(pf_contrasenia_IniciarSesion.getPassword()));

                ResultSet resultado = nuevoStatementPreparado.executeQuery();

                if (resultado.next()) {

                    

                    Usuario userFinal = encontrarAdmin();
                    

                    agregarVuelos n = new agregarVuelos();
                    n.setVisible(true);

                    this.dispose();

                } else {
                    CredencialesIncorrectas n = new CredencialesIncorrectas();
                    n.setVisible(true);
                }

                nuevaConexion.close();
                nuevoStatementPreparado.close();
                resultado.close();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Credenciales incorrectas, intente nuevamente");

            }
        } else {
            try {

                Connection nuevaConexion = DriverManager.getConnection(
                        "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                        "root",
                        "Fide123.");

                String consulta_inicio = "SELECT correoelectronico,password"
                        + " FROM usuarios WHERE correoelectronico = ? AND password = ?";

                PreparedStatement nuevoStatementPreparado = nuevaConexion.prepareStatement(consulta_inicio);

                nuevoStatementPreparado.setString(1, txf_correo_electronico_IniciarSesion.getText());

                nuevoStatementPreparado.setString(2, String.copyValueOf(pf_contrasenia_IniciarSesion.getPassword()));

                ResultSet resultado = nuevoStatementPreparado.executeQuery();

                if (resultado.next()) {

                   

                    Usuario userFinal = encontrarUser();

                    VentanaPrincipal abrirVentanaPrincipal = new VentanaPrincipal(userFinal, null, null);
                    abrirVentanaPrincipal.setVisible(true);

                    this.dispose();

                } else {
                    CredencialesIncorrectas n = new CredencialesIncorrectas();
                    n.setVisible(true);
                }

                nuevaConexion.close();
                nuevoStatementPreparado.close();
                resultado.close();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Credenciales incorrectas, intente nuevamente");

            }
        }


    }//GEN-LAST:event_lbl_btn_AccederMouseClicked

    private void lbl_btn_Registrarse_IniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_Registrarse_IniciarSesionMouseEntered
        // TODO add your handling code here:
        pnl_btn_Registrarse_IniciarSesion.setBackground(new Color(79, 93, 255));
    }//GEN-LAST:event_lbl_btn_Registrarse_IniciarSesionMouseEntered

    private void lbl_btn_Registrarse_IniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_Registrarse_IniciarSesionMouseExited
        pnl_btn_Registrarse_IniciarSesion.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_Registrarse_IniciarSesionMouseExited

    private void lbl_btn_Registrarse_IniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_Registrarse_IniciarSesionMouseClicked

        this.dispose();
        Registro abrirRegistro = new Registro();
        abrirRegistro.setVisible(true);
    }//GEN-LAST:event_lbl_btn_Registrarse_IniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public Usuario encontrarUser() {

        Usuario user = new Usuario();

        try {
            Connection nuevaConexion = DriverManager.getConnection(
                    "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                    "root",
                    "Fide123.");

            String consulta_user = "SELECT nombre,apellidos,edad,correoelectronico,password,aerolineaspreferidas,clasepreferida,comida,entretenimiento"
                    + " FROM usuarios WHERE correoelectronico = ?";

            PreparedStatement nuevoStatementPreparado = nuevaConexion.prepareStatement(consulta_user);

            nuevoStatementPreparado.setString(1, txf_correo_electronico_IniciarSesion.getText());

            ResultSet resultado = nuevoStatementPreparado.executeQuery();

            while (resultado.next()) {

                user.setNombre(resultado.getString("nombre"));
                user.setApellidos(resultado.getString("apellidos"));
                user.setEdad(resultado.getString("edad"));
                user.setCorreoelectronico(resultado.getString("correoelectronico"));
                user.setPassword(resultado.getString("password"));
                user.setAerolineaspreferidas(resultado.getString("aerolineaspreferidas"));
                user.setClasepreferida(resultado.getString("clasepreferida"));
                user.setComida(resultado.getString("comida"));
                user.setEntretenimiento(resultado.getString("entretenimiento"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
        Usuario userElegido = new Usuario(
                user.getNombre(),
                user.getApellidos(),
                user.getEdad(),
                user.getCorreoelectronico(),
                user.getPassword(),
                user.getAerolineaspreferidas(),
                user.getClasepreferida(),
                user.getComida(),
                user.getEntretenimiento());

        return userElegido;
    }

    public Usuario encontrarAdmin() {

        Usuario user = new Usuario();

        try {
            Connection nuevaConexion = DriverManager.getConnection(
                    "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                    "root",
                    "Fide123.");

            String consulta_user = "SELECT nombre,apellidos,correoelectronico,password"
                    + " FROM admins WHERE correoelectronico = ?";

            PreparedStatement nuevoStatementPreparado = nuevaConexion.prepareStatement(consulta_user);

            nuevoStatementPreparado.setString(1, txf_correo_electronico_IniciarSesion.getText());

            ResultSet resultado = nuevoStatementPreparado.executeQuery();

            while (resultado.next()) {

                user.setNombre(resultado.getString("nombre"));
                user.setApellidos(resultado.getString("apellidos"));
                user.setCorreoelectronico(resultado.getString("correoelectronico"));
                user.setPassword(resultado.getString("password"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

        Usuario userElegido = new Usuario();
        userElegido.setNombre(user.getNombre());
        userElegido.setApellidos(user.getApellidos());
        userElegido.setCorreoelectronico(user.getCorreoelectronico());
        userElegido.setPassword(user.getPassword());

        return userElegido;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JCheckBox chbx_adminLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Iniciar_Sesion;
    private javax.swing.JLabel lbl_btn_Acceder;
    private javax.swing.JLabel lbl_btn_Registrarse_IniciarSesion;
    private javax.swing.JLabel lbl_btn_SALIR;
    private javax.swing.JLabel lbl_fideairlines;
    private javax.swing.JLabel lbl_olvide_mi_contrasenia;
    private javax.swing.JPasswordField pf_contrasenia_IniciarSesion;
    private javax.swing.JPanel pnl_Azul_IniciarSesion;
    private javax.swing.JPanel pnl_barra_salir;
    private javax.swing.JPanel pnl_btn_Acceder;
    private javax.swing.JPanel pnl_btn_Registrarse_IniciarSesion;
    private javax.swing.JPanel pnl_btn_salir;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txf_correo_electronico_IniciarSesion;
    // End of variables declaration//GEN-END:variables
}
