/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanasModelo;


import Ventanas.InicioSesion.InicioSesion;
import java.awt.Color;

/**
 *
 * @author ricar
 */
public class ventanaModeloAzul extends javax.swing.JFrame {

    /**
     * Creates new form agregarVuelos
     */
    int xmouse, ymouse;

    public ventanaModeloAzul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_btn_salir = new javax.swing.JPanel();
        lbl_btn_salir = new javax.swing.JLabel();
        pnl_barra_salida = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 51, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_btn_salir.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_salir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbl_btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_salir.setText("X");
        lbl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        pnl_barra_salida.setBackground(new java.awt.Color(43, 51, 139));
        pnl_barra_salida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salidaMouseDragged(evt);
            }
        });
        pnl_barra_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salidaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_barra_salidaLayout = new javax.swing.GroupLayout(pnl_barra_salida);
        pnl_barra_salida.setLayout(pnl_barra_salidaLayout);
        pnl_barra_salidaLayout.setHorizontalGroup(
            pnl_barra_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnl_barra_salidaLayout.setVerticalGroup(
            pnl_barra_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(pnl_barra_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_barra_salidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salidaMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_barra_salidaMousePressed

    private void pnl_barra_salidaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salidaMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salidaMouseDragged

    private void lbl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.white);
        lbl_btn_salir.setForeground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_salirMouseEntered

    private void lbl_btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseClicked
        // TODO add your handling code here:

        this.dispose();
        InicioSesion n = new InicioSesion();
        n.setVisible(true);
    }//GEN-LAST:event_lbl_btn_salirMouseClicked

    private void lbl_btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_salirMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(new Color(43, 51, 139));
        lbl_btn_salir.setForeground(Color.white);
    }//GEN-LAST:event_lbl_btn_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaModeloAzul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaModeloAzul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaModeloAzul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaModeloAzul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaModeloAzul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_btn_salir;
    private javax.swing.JPanel pnl_barra_salida;
    private javax.swing.JPanel pnl_btn_salir;
    // End of variables declaration//GEN-END:variables
}
