/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MiPerfil;

import Clases.Reserva;
import Ventanas.Registro.*;
import Clases.Usuario;
import Ventanas.Auxiliares.Hilo_RegistroCompleto;
import Ventanas.Auxiliares.RegistroCompleto;
import Ventanas.Errores.ApellidosIncorrectos;
import Ventanas.Errores.CorreoIncorrecto;
import Ventanas.Errores.NombreIncorrecto;
import Ventanas.Errores.OcurreError;
import Ventanas.Errores.PasswordIncorrecta;
import Ventanas.Errores.UsuarioYaRegistrado;
import Ventanas.Errores.contraseniasDiferentes;
import Ventanas.InicioSesion.InicioSesion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class Editar_datos extends javax.swing.JFrame {

    int xmouse, ymouse;

    private Usuario user;
    private Reserva reserva;

    public Editar_datos(Usuario user,Reserva reserva) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        this.reserva =reserva;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        pnl_blanco_registrese = new javax.swing.JPanel();
        lbl_Registrese = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_apellidos = new javax.swing.JTextField();
        txf_correo_electronico = new javax.swing.JTextField();
        pf_contrasenia = new javax.swing.JPasswordField();
        pf_confirmar_contrasenia = new javax.swing.JPasswordField();
        pnl_btn_registrarse = new javax.swing.JPanel();
        lbl_btn_registrarse = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        cbx_Edad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        pnl_azul_logo = new javax.swing.JPanel();
        lbl_fideairlines = new javax.swing.JLabel();
        lbl_logo_fideairlines = new javax.swing.JLabel();
        pnl_barra_salir = new javax.swing.JPanel();
        pnl_btn_salir = new javax.swing.JPanel();
        lbl_btn_SALIR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_blanco_registrese.setBackground(new java.awt.Color(255, 255, 255));
        pnl_blanco_registrese.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Registrese.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lbl_Registrese.setForeground(new java.awt.Color(43, 51, 139));
        lbl_Registrese.setText("Editar Datos personales");
        pnl_blanco_registrese.add(lbl_Registrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, -1));

        txf_nombre.setForeground(new java.awt.Color(204, 204, 204));
        txf_nombre.setText("Nombre");
        txf_nombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txf_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txf_nombreMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txf_nombreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txf_nombreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txf_nombreMouseReleased(evt);
            }
        });
        txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nombreActionPerformed(evt);
            }
        });
        pnl_blanco_registrese.add(txf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 108, 135, 30));

        txf_apellidos.setForeground(new java.awt.Color(204, 204, 204));
        txf_apellidos.setText("Apellidos");
        txf_apellidos.setBorder(null);
        txf_apellidos.setPreferredSize(new java.awt.Dimension(64, 18));
        txf_apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txf_apellidosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txf_apellidosMousePressed(evt);
            }
        });
        txf_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_apellidosActionPerformed(evt);
            }
        });
        pnl_blanco_registrese.add(txf_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 106, 135, 30));

        txf_correo_electronico.setForeground(new java.awt.Color(204, 204, 204));
        txf_correo_electronico.setText("Correo Electronico");
        txf_correo_electronico.setBorder(null);
        txf_correo_electronico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txf_correo_electronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txf_correo_electronicoMousePressed(evt);
            }
        });
        txf_correo_electronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_correo_electronicoActionPerformed(evt);
            }
        });
        pnl_blanco_registrese.add(txf_correo_electronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 288, 30));

        pf_contrasenia.setForeground(new java.awt.Color(204, 204, 204));
        pf_contrasenia.setText("********");
        pf_contrasenia.setBorder(null);
        pf_contrasenia.setPreferredSize(new java.awt.Dimension(64, 18));
        pf_contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pf_contraseniaMousePressed(evt);
            }
        });
        pnl_blanco_registrese.add(pf_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        pf_confirmar_contrasenia.setForeground(new java.awt.Color(204, 204, 204));
        pf_confirmar_contrasenia.setText("********");
        pf_confirmar_contrasenia.setBorder(null);
        pf_confirmar_contrasenia.setPreferredSize(new java.awt.Dimension(64, 18));
        pf_confirmar_contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pf_confirmar_contraseniaMousePressed(evt);
            }
        });
        pnl_blanco_registrese.add(pf_confirmar_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 100, 30));

        pnl_btn_registrarse.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_registrarse.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lbl_btn_registrarse.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_registrarse.setText("GUARDAR CAMBIOS");
        lbl_btn_registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_registrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_registrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_registrarseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_registrarseLayout = new javax.swing.GroupLayout(pnl_btn_registrarse);
        pnl_btn_registrarse.setLayout(pnl_btn_registrarseLayout);
        pnl_btn_registrarseLayout.setHorizontalGroup(
            pnl_btn_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );
        pnl_btn_registrarseLayout.setVerticalGroup(
            pnl_btn_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pnl_blanco_registrese.add(pnl_btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 387, -1, -1));
        pnl_blanco_registrese.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 10));
        pnl_blanco_registrese.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 10));
        pnl_blanco_registrese.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 10));
        pnl_blanco_registrese.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 10));
        pnl_blanco_registrese.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 10));

        cbx_Edad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        cbx_Edad.setBorder(null);
        pnl_blanco_registrese.add(cbx_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Edad");
        pnl_blanco_registrese.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        pnl_blanco_registrese.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, 10));

        background.add(pnl_blanco_registrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 350, 470));

        pnl_azul_logo.setBackground(new java.awt.Color(43, 51, 139));
        pnl_azul_logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_fideairlines.setFont(new java.awt.Font("Roboto Medium", 2, 36)); // NOI18N
        lbl_fideairlines.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fideairlines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fideairlines.setText("FIDE AIRLINES");
        pnl_azul_logo.add(lbl_fideairlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 180, 440, 100));

        lbl_logo_fideairlines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGO 1.png"))); // NOI18N
        pnl_azul_logo.add(lbl_logo_fideairlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 330, 218));

        background.add(pnl_azul_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 500));

        pnl_barra_salir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_barra_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMouseDragged(evt);
            }
        });
        pnl_barra_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMousePressed(evt);
            }
        });

        pnl_btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        pnl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btn_salirMouseEntered(evt);
            }
        });

        lbl_btn_SALIR.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        lbl_btn_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_SALIR.setText("X");
        lbl_btn_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_barra_salirLayout = new javax.swing.GroupLayout(pnl_barra_salir);
        pnl_barra_salir.setLayout(pnl_barra_salirLayout);
        pnl_barra_salirLayout.setHorizontalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_salirLayout.createSequentialGroup()
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 770, Short.MAX_VALUE))
        );
        pnl_barra_salirLayout.setVerticalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(pnl_barra_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txf_nombreActionPerformed

    private void txf_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_apellidosActionPerformed

    private void pnl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btn_salirMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_pnl_btn_salirMouseEntered

    private void pnl_barra_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();

    }//GEN-LAST:event_pnl_barra_salirMousePressed

    private void pnl_barra_salirMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salirMouseDragged

    private void lbl_btn_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.blue);
        lbl_btn_SALIR.setForeground(Color.WHITE);

    }//GEN-LAST:event_lbl_btn_SALIRMouseEntered

    private void lbl_btn_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lbl_btn_SALIRMouseClicked

    private void lbl_btn_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.white);
        lbl_btn_SALIR.setForeground(Color.BLACK);

    }//GEN-LAST:event_lbl_btn_SALIRMouseExited

    private void txf_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_nombreMousePressed
        if (txf_nombre.getText().equals("Nombre")) {
            txf_nombre.setText("");
            txf_nombre.setForeground(Color.BLACK);
        } else if (txf_nombre.getText().isEmpty()) {
            txf_nombre.setForeground(Color.LIGHT_GRAY);
            txf_nombre.setText("Nombre");
        }

        if (txf_correo_electronico.getText().isEmpty()) {
            txf_correo_electronico.setForeground(Color.lightGray);
            txf_correo_electronico.setText("Correo Electronico");
        }
        if (txf_apellidos.getText().isEmpty()) {
            txf_apellidos.setForeground(Color.lightGray);
            txf_apellidos.setText("Apellidos");
        }
        if (String.valueOf(pf_contrasenia.getPassword()).isEmpty()) {
            pf_contrasenia.setText("********");
            pf_contrasenia.setForeground(Color.lightGray);
        }
        if (String.valueOf(pf_confirmar_contrasenia.getPassword()).isEmpty()) {
            pf_confirmar_contrasenia.setText("********");
            pf_confirmar_contrasenia.setForeground(Color.lightGray);
        }

    }//GEN-LAST:event_txf_nombreMousePressed

    private void txf_apellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_apellidosMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_txf_apellidosMousePressed

    private void txf_correo_electronicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_correo_electronicoMousePressed

        if (txf_correo_electronico.getText().isEmpty()) {
            txf_correo_electronico.setForeground(Color.lightGray);
            txf_correo_electronico.setText("Correo Electronico");
        } else if (txf_correo_electronico.getText().equals("Correo Electronico")) {
            txf_correo_electronico.setText("");
            txf_correo_electronico.setForeground(Color.BLACK);
        }

        if (txf_nombre.getText().isEmpty()) {
            txf_nombre.setForeground(Color.LIGHT_GRAY);
            txf_nombre.setText("Nombre");
        }
        if (txf_apellidos.getText().isEmpty()) {
            txf_apellidos.setForeground(Color.lightGray);
            txf_apellidos.setText("Apellidos");
        }
        if (String.valueOf(pf_contrasenia.getPassword()).isEmpty()) {
            pf_contrasenia.setText("********");
            pf_contrasenia.setForeground(Color.lightGray);
        }
        if (String.valueOf(pf_confirmar_contrasenia.getPassword()).isEmpty()) {
            pf_confirmar_contrasenia.setText("********");
            pf_confirmar_contrasenia.setForeground(Color.lightGray);
        }

    }//GEN-LAST:event_txf_correo_electronicoMousePressed

    private void pf_contraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_contraseniaMousePressed
        if (String.valueOf(pf_contrasenia.getPassword()).equals("********")) {
            pf_contrasenia.setText("");
            pf_contrasenia.setForeground(Color.BLACK);
        } else if (String.valueOf(pf_contrasenia.getPassword()).isEmpty()) {
            pf_contrasenia.setText("********");
            pf_contrasenia.setForeground(Color.lightGray);
        }

        if (String.valueOf(pf_confirmar_contrasenia.getPassword()).isEmpty()) {
            pf_confirmar_contrasenia.setText("********");
            pf_confirmar_contrasenia.setForeground(Color.lightGray);
        }
        if (txf_nombre.getText().isEmpty()) {
            txf_nombre.setForeground(Color.LIGHT_GRAY);
            txf_nombre.setText("Nombre");
        }
        if (txf_apellidos.getText().isEmpty()) {
            txf_apellidos.setForeground(Color.lightGray);
            txf_apellidos.setText("Apellidos");
        }
        if (txf_correo_electronico.getText().isEmpty()) {
            txf_correo_electronico.setForeground(Color.lightGray);
            txf_correo_electronico.setText("Correo Electronico");
        }

    }//GEN-LAST:event_pf_contraseniaMousePressed

    private void pf_confirmar_contraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_confirmar_contraseniaMousePressed
        if (String.valueOf(pf_confirmar_contrasenia.getPassword()).equals("********")) {
            pf_confirmar_contrasenia.setText("");
            pf_confirmar_contrasenia.setForeground(Color.BLACK);
        } else if (String.valueOf(pf_confirmar_contrasenia.getPassword()).isEmpty()) {
            pf_confirmar_contrasenia.setText("********");
            pf_confirmar_contrasenia.setForeground(Color.lightGray);
        }

        if (txf_nombre.getText().isEmpty()) {
            txf_nombre.setForeground(Color.LIGHT_GRAY);
            txf_nombre.setText("Nombre");
        }
        if (txf_apellidos.getText().isEmpty()) {
            txf_apellidos.setForeground(Color.lightGray);
            txf_apellidos.setText("Apellidos");
        }
        if (txf_correo_electronico.getText().isEmpty()) {
            txf_correo_electronico.setForeground(Color.lightGray);
            txf_correo_electronico.setText("Correo Electronico");
        }
        if (String.valueOf(pf_contrasenia.getPassword()).isEmpty()) {
            pf_contrasenia.setText("********");
            pf_contrasenia.setForeground(Color.lightGray);
        }


    }//GEN-LAST:event_pf_confirmar_contraseniaMousePressed

    private void txf_correo_electronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_correo_electronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_correo_electronicoActionPerformed

    private void txf_nombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_nombreMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_txf_nombreMouseExited

    private void txf_nombreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_nombreMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txf_nombreMouseReleased

    private void txf_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_nombreMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txf_nombreMouseClicked

    private void lbl_btn_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_registrarseMouseClicked

        Usuario anterior = new Usuario();

        anterior.setCorreoelectronico(user.getCorreoelectronico());

        if (verificar_Nombre(txf_nombre.getText())) {
            if (verificar_Apellidos(txf_apellidos.getText())) {
                if (verificar_Email(txf_correo_electronico.getText())) {
                    if (verificar_Password(String.valueOf(pf_contrasenia.getPassword()))) {
                        if (String.valueOf(pf_contrasenia.getPassword()).equals(String.valueOf(pf_confirmar_contrasenia.getPassword()))) {

                            Usuario nuevoUsuario = new Usuario();

                            nuevoUsuario.setNombre(txf_nombre.getText());

                            nuevoUsuario.setApellidos(txf_apellidos.getText());

                            nuevoUsuario.setCorreoelectronico(txf_correo_electronico.getText().toLowerCase());

                            nuevoUsuario.setEdad(String.valueOf(cbx_Edad.getSelectedItem()));

                            nuevoUsuario.setPassword(String.valueOf(pf_confirmar_contrasenia.getPassword()));

                            try {
                                Connection nuevaConexion = DriverManager.getConnection(
                                        "jdbc:mysql://localhost/fideairlines?serverTimezone=UTC",
                                        "root",
                                        "Fide123.");

                                String update_datos = "UPDATE usuarios SET nombre = ? "
                                        + ",apellidos = ?, edad = ?, correoelectronico = ?,password = ?  WHERE correoelectronico = ?";

                                PreparedStatement nuevoStatementePreparado = nuevaConexion.prepareStatement(update_datos);

                                nuevoStatementePreparado.setString(1, nuevoUsuario.getNombre());
                                nuevoStatementePreparado.setString(2, nuevoUsuario.getApellidos());
                                nuevoStatementePreparado.setString(3, nuevoUsuario.getEdad());
                                nuevoStatementePreparado.setString(4, nuevoUsuario.getCorreoelectronico());
                                nuevoStatementePreparado.setString(5, nuevoUsuario.getPassword());
                                nuevoStatementePreparado.setString(6, anterior.getCorreoelectronico());
                                
                                nuevoStatementePreparado.executeUpdate();
                                

                                nuevaConexion.close();
                                nuevoStatementePreparado.close();
                                
                                user.setNombre(nuevoUsuario.getNombre());
                                user.setApellidos(nuevoUsuario.getApellidos());
                                user.setEdad(nuevoUsuario.getEdad());
                                user.setCorreoelectronico(nuevoUsuario.getCorreoelectronico());
                                this.dispose();
                                
                                InformacionPersonal n = new InformacionPersonal(user,reserva);
                                n.setVisible(true);
                            } catch (SQLException ex) {
                                Logger.getLogger(Editar_datos.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            contraseniasDiferentes error1 = new contraseniasDiferentes();
                            error1.setVisible(true);
                        }

                    } else {
                        PasswordIncorrecta error4 = new PasswordIncorrecta();
                        error4.setVisible(true);
                    }
                } else {
                    CorreoIncorrecto error3 = new CorreoIncorrecto();
                    error3.setVisible(true);

                }
            } else {
                ApellidosIncorrectos error2 = new ApellidosIncorrectos();
                error2.setVisible(true);
            }

        } else {
            NombreIncorrecto error1 = new NombreIncorrecto();
            error1.setVisible(true);

        }
    }//GEN-LAST:event_lbl_btn_registrarseMouseClicked

    private void lbl_btn_registrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_registrarseMouseEntered
        // TODO add your handling code here:

        pnl_btn_registrarse.setBackground(new Color(79, 93, 255));

    }//GEN-LAST:event_lbl_btn_registrarseMouseEntered

    private void lbl_btn_registrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_registrarseMouseExited
        pnl_btn_registrarse.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_registrarseMouseExited

    private void txf_apellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txf_apellidosMouseClicked
        // TODO add your handling code here:
        if (txf_apellidos.getText().equals("Apellidos")) {
            txf_apellidos.setText("");
            txf_apellidos.setForeground(Color.BLACK);
        } else if (txf_apellidos.getText().isEmpty()) {
            txf_apellidos.setForeground(Color.lightGray);
            txf_apellidos.setText("Apellidos");
        }

        if (txf_nombre.getText().isEmpty()) {
            txf_nombre.setForeground(Color.LIGHT_GRAY);
            txf_nombre.setText("Nombre");
        }
        if (txf_correo_electronico.getText().isEmpty()) {
            txf_correo_electronico.setForeground(Color.lightGray);
            txf_correo_electronico.setText("Correo Electronico");
        }
        if (String.valueOf(pf_contrasenia.getPassword()).isEmpty()) {
            pf_contrasenia.setText("********");
            pf_contrasenia.setForeground(Color.lightGray);
        }
        if (String.valueOf(pf_confirmar_contrasenia.getPassword()).isEmpty()) {
            pf_confirmar_contrasenia.setText("********");
            pf_confirmar_contrasenia.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_txf_apellidosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_datos(null,null).setVisible(true);
            }
        });

    }

    public boolean verificar_Nombre(String nombre) {

        Pattern patron = Pattern.compile("^[A-Za-z ]+$");

        Matcher mat = patron.matcher(nombre);
        return mat.find();

    }

    public boolean verificar_Apellidos(String apellidos) {

        Pattern patron = Pattern.compile("^[A-Za-z ]+$");

        Matcher mat = patron.matcher(apellidos);
        return mat.find();

    }

    public boolean verificar_Email(String correo) {

        Pattern patron = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");

        Matcher mat = patron.matcher(correo);
        return mat.find();

    }

    public boolean verificar_Password(String password) {

        Pattern patron = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?.&])[A-Za-z\\d@$!%*.?&]{8,}$");

        Matcher mat = patron.matcher(password);
        return mat.find();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> cbx_Edad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_Registrese;
    private javax.swing.JLabel lbl_btn_SALIR;
    private javax.swing.JLabel lbl_btn_registrarse;
    private javax.swing.JLabel lbl_fideairlines;
    private javax.swing.JLabel lbl_logo_fideairlines;
    private javax.swing.JPasswordField pf_confirmar_contrasenia;
    private javax.swing.JPasswordField pf_contrasenia;
    private javax.swing.JPanel pnl_azul_logo;
    private javax.swing.JPanel pnl_barra_salir;
    private javax.swing.JPanel pnl_blanco_registrese;
    private javax.swing.JPanel pnl_btn_registrarse;
    private javax.swing.JPanel pnl_btn_salir;
    private javax.swing.JTextField txf_apellidos;
    private javax.swing.JTextField txf_correo_electronico;
    private javax.swing.JTextField txf_nombre;
    // End of variables declaration//GEN-END:variables
}
