/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MiPerfil;

import Clases.Reserva;
import Clases.Usuario;
import Funcionalidades.PreferenciasUsuario;
import java.awt.Color;

/**
 *
 * @author ricar
 */
public class InformacionPersonal extends javax.swing.JFrame {

    /**
     * Creates new form InformacionPersonal
     */
    
    private int xmouse,ymouse;
    
    private Usuario user;
    private Reserva reserva;
    
    public InformacionPersonal(Usuario user,Reserva reserva) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        this.reserva= reserva;
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_nombreUsuario = new javax.swing.JLabel();
        lbl_ApellidosUsuario = new javax.swing.JLabel();
        lbl_edadUsuario = new javax.swing.JLabel();
        lbl_correoUsuario = new javax.swing.JLabel();
        lbl_aerolineaUsuario = new javax.swing.JLabel();
        lbl_claseUsuario = new javax.swing.JLabel();
        lbl_comidaUsuario = new javax.swing.JLabel();
        lbl_EntretenimientoUsuario = new javax.swing.JLabel();
        pnl_btn_editardatos = new javax.swing.JPanel();
        lbl_btn_editardatos = new javax.swing.JLabel();
        pnl_btn_editarpreferencias = new javax.swing.JPanel();
        lbl_btn_editarpreferencias = new javax.swing.JLabel();
        pnl_barra_salir = new javax.swing.JPanel();
        pnl_btn_salir = new javax.swing.JPanel();
        lbl_btn_SALIR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 51, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombreUsuario.setText("nombre");
        jPanel2.add(lbl_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 48, -1, -1));

        lbl_ApellidosUsuario.setText("apellidos");
        jPanel2.add(lbl_ApellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 84, -1, -1));

        lbl_edadUsuario.setText("edad");
        jPanel2.add(lbl_edadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 118, -1, -1));

        lbl_correoUsuario.setText("correoelectronico");
        jPanel2.add(lbl_correoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 156, -1, -1));

        lbl_aerolineaUsuario.setText("aerolinea preferida");
        jPanel2.add(lbl_aerolineaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 190, -1, -1));

        lbl_claseUsuario.setText("clase de vuelo preferida");
        jPanel2.add(lbl_claseUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 218, -1, -1));

        lbl_comidaUsuario.setText("servicio de comida");
        jPanel2.add(lbl_comidaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 246, -1, -1));

        lbl_EntretenimientoUsuario.setText("servicio de entretenimiento");
        jPanel2.add(lbl_EntretenimientoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 274, -1, -1));

        pnl_btn_editardatos.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_editardatos.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbl_btn_editardatos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_editardatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_editardatos.setText("Editar datos");
        lbl_btn_editardatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_editardatosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_editardatosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_editardatosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_editardatosLayout = new javax.swing.GroupLayout(pnl_btn_editardatos);
        pnl_btn_editardatos.setLayout(pnl_btn_editardatosLayout);
        pnl_btn_editardatosLayout.setHorizontalGroup(
            pnl_btn_editardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_editardatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_editardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_editardatosLayout.setVerticalGroup(
            pnl_btn_editardatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_editardatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_editardatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnl_btn_editardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 130, -1));

        pnl_btn_editarpreferencias.setBackground(new java.awt.Color(43, 51, 139));

        lbl_btn_editarpreferencias.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lbl_btn_editarpreferencias.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_editarpreferencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_editarpreferencias.setText("Editar preferencias");
        lbl_btn_editarpreferencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_editarpreferenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_editarpreferenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_editarpreferenciasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_editarpreferenciasLayout = new javax.swing.GroupLayout(pnl_btn_editarpreferencias);
        pnl_btn_editarpreferencias.setLayout(pnl_btn_editarpreferenciasLayout);
        pnl_btn_editarpreferenciasLayout.setHorizontalGroup(
            pnl_btn_editarpreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_btn_editarpreferencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        pnl_btn_editarpreferenciasLayout.setVerticalGroup(
            pnl_btn_editarpreferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_editarpreferenciasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_editarpreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(pnl_btn_editarpreferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 760, 320));

        pnl_barra_salir.setBackground(new java.awt.Color(43, 51, 139));
        pnl_barra_salir.setForeground(new java.awt.Color(43, 51, 139));
        pnl_barra_salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMouseDragged(evt);
            }
        });
        pnl_barra_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_barra_salirMousePressed(evt);
            }
        });

        pnl_btn_salir.setBackground(new java.awt.Color(43, 51, 139));
        pnl_btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_btn_salirMouseEntered(evt);
            }
        });

        lbl_btn_SALIR.setFont(new java.awt.Font("Roboto Thin", 0, 18)); // NOI18N
        lbl_btn_SALIR.setForeground(new java.awt.Color(255, 255, 255));
        lbl_btn_SALIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_btn_SALIR.setText("X");
        lbl_btn_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_btn_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_btn_SALIRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnl_btn_salirLayout = new javax.swing.GroupLayout(pnl_btn_salir);
        pnl_btn_salir.setLayout(pnl_btn_salirLayout);
        pnl_btn_salirLayout.setHorizontalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_btn_salirLayout.setVerticalGroup(
            pnl_btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_btn_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_btn_SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnl_barra_salirLayout = new javax.swing.GroupLayout(pnl_barra_salir);
        pnl_barra_salir.setLayout(pnl_barra_salirLayout);
        pnl_barra_salirLayout.setHorizontalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_barra_salirLayout.createSequentialGroup()
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 770, Short.MAX_VALUE))
        );
        pnl_barra_salirLayout.setVerticalGroup(
            pnl_barra_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_barra_salirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnl_barra_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_btn_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseClicked
        // TODO add your handling code here:
        this.dispose();
        MiPerfil n = new MiPerfil(user,reserva);
        n.setVisible(true);
    }//GEN-LAST:event_lbl_btn_SALIRMouseClicked

    private void lbl_btn_SALIRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseEntered
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(Color.WHITE);
        lbl_btn_SALIR.setForeground(Color.BLUE);
    }//GEN-LAST:event_lbl_btn_SALIRMouseEntered

    private void lbl_btn_SALIRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_SALIRMouseExited
        // TODO add your handling code here:
        pnl_btn_salir.setBackground(new Color(43, 51, 139));
        lbl_btn_SALIR.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbl_btn_SALIRMouseExited

    private void pnl_btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_btn_salirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnl_btn_salirMouseEntered

    private void pnl_barra_salirMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }//GEN-LAST:event_pnl_barra_salirMouseDragged

    private void pnl_barra_salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_barra_salirMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_pnl_barra_salirMousePressed

    private void lbl_btn_editardatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editardatosMouseClicked
        Editar_datos n = new Editar_datos(user,reserva);
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_btn_editardatosMouseClicked

    private void lbl_btn_editardatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editardatosMouseEntered
       pnl_btn_editardatos.setBackground(new Color(79, 93, 255));
    }//GEN-LAST:event_lbl_btn_editardatosMouseEntered

    private void lbl_btn_editardatosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editardatosMouseExited
       
        pnl_btn_editardatos.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_editardatosMouseExited

    private void lbl_btn_editarpreferenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editarpreferenciasMouseEntered
       pnl_btn_editarpreferencias.setBackground(new Color(79, 93, 255));
    }//GEN-LAST:event_lbl_btn_editarpreferenciasMouseEntered

    private void lbl_btn_editarpreferenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editarpreferenciasMouseExited
        pnl_btn_editardatos.setBackground(new Color(43, 51, 139));
    }//GEN-LAST:event_lbl_btn_editarpreferenciasMouseExited

    private void lbl_btn_editarpreferenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_btn_editarpreferenciasMouseClicked
        
        PreferenciasUsuario n = new PreferenciasUsuario(user);
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_btn_editarpreferenciasMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void mostrarDatos (){
        lbl_nombreUsuario.setText("Nombre: "+user.getNombre());
        lbl_ApellidosUsuario.setText("Apellidos: "+user.getApellidos());
        lbl_edadUsuario.setText("Edad: "+user.getEdad());
        lbl_correoUsuario.setText("Correo electronico: "+user.getCorreoelectronico());
        lbl_aerolineaUsuario.setText("Aerolinea preferida: "+user.getAerolineaspreferidas());
        lbl_claseUsuario.setText("Clase de vuelo preferida: "+user.getClasepreferida());
        lbl_comidaUsuario.setText("Servicio de comida: "+user.getComida());
        lbl_EntretenimientoUsuario.setText("Servicio de entretenimiento: "+user.getEntretenimiento());
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionPersonal(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_ApellidosUsuario;
    private javax.swing.JLabel lbl_EntretenimientoUsuario;
    private javax.swing.JLabel lbl_aerolineaUsuario;
    private javax.swing.JLabel lbl_btn_SALIR;
    private javax.swing.JLabel lbl_btn_editardatos;
    private javax.swing.JLabel lbl_btn_editarpreferencias;
    private javax.swing.JLabel lbl_claseUsuario;
    private javax.swing.JLabel lbl_comidaUsuario;
    private javax.swing.JLabel lbl_correoUsuario;
    private javax.swing.JLabel lbl_edadUsuario;
    private javax.swing.JLabel lbl_nombreUsuario;
    private javax.swing.JPanel pnl_barra_salir;
    private javax.swing.JPanel pnl_btn_editardatos;
    private javax.swing.JPanel pnl_btn_editarpreferencias;
    private javax.swing.JPanel pnl_btn_salir;
    // End of variables declaration//GEN-END:variables
}
